typography_spectrum: 0.63772790459916
color:
  saturation: 0.22248017392121255
  lightness: 0.946596757741645
  brandStrength: 0.4666069250088185
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  rhythmicContrast: 0.4512314123567194
layout_spectrum: 0.9810136565938592
author:
  name: Jorge Alves Lino
  email: jorge@strp.nl
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b5e58247-df86-49c3-bfaf-14aaad221aef.png
name: STRP CITY
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e57c7d75-3dfb-4e91-8609-c5dc4a533763.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
