color:
  saturation: 0.6144755
  brandStrength: 0.853741
  rhythmicContrast: 0.6016998
  lightness: 0.8477352
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.0001812405
typography_spectrum: 0.3452623
name: STRP CITY
