layout_spectrum: 0.0001812405
typography_spectrum: 0.3452623
color:
  saturation: 0.6144755
  lightness: 0.8477352
  brandStrength: 0.853741
  rhythmicContrast: 0.6016998
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: STRP CITY
