collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3452623
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.853741
  brandColors:
    - '#510208'
    - '#FE012F'
    - '#FF9A5F'
    - '#FF3F59'
    - '#FFF773'
  rhythmicContrast: 1
layout_spectrum: 0.9833512
name: STRP CITY
